[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "racehorses"
version = "0.0.1"
dependencies = [
    "PyYAML",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
racehorses = "racehorses.__main__.main"
